### PR TITLE
resolve missing egrid facility fields for 2020 and 2021

### LINKED ISSUE #153: eGRID 2020 column name change
Stewi's getInventoryFacilities method for "eGRID" returns a data frame using row 1's column names from "PLNT16" or "PLNT20" worksheet of the respectively downloaded Excel workbook (e.g., 'egrid2016.xlsx' and 'eGRID2020_Data_v2.xlsx'); however, these names fail a consistency check between 2016 and 2020. Row 2 of the worksheet includes a keyword for the column, which appears to be consistent. This creates a challenge for data users when dealing with multi-annual datasets (i.e., I have to write a check for multiple column names rather than a single check against the keyword).

Testing Stewi's getInventoryFacilities method for "eGRID" 2020, it seems to be missing the primary fuel category.

Reproducible example:

```py
>>> import stewi
>>> df_2016 = stewi.getInventoryFacilities("eGRID", 2016)
>>> df_2020 = stewi.getInventoryFacilities("eGRID", 2020)
>>> df_2016.columns
Index(['FacilityID', 'FacilityName', 'Address', 'City', 'State', 'Zip',
       'Latitude', 'Longitude', 'County', 'NAICS', 'SIC', 'UrbanRural',
       'Plant operator name', 'Balancing Authority Name',
       'Balancing Authority Code', 'NERC region acronym',
       'eGRID subregion acronym', 'Plant primary fuel',
       'Plant primary coal/oil/gas/ other fossil fuel category',  # Fuel category
       'Plant coal generation percent (resource mix)',
       'Plant oil generation percent (resource mix)',
       'Plant gas generation percent (resource mix)',
       'Plant nuclear generation percent (resource mix)',
       'Plant hydro generation percent (resource mix)',
       'Plant biomass generation percent (resource mix)',
       'Plant wind generation percent (resource mix)',
       'Plant solar generation percent (resource mix)',
       'Plant geothermal generation percent (resource mix)',
       'Plant other fossil generation percent (resource mix)',
       'Plant other unknown / purchased fuel generation percent (resource mix)'],
      dtype='object')
>>> df_2020.columns
Index(['FacilityID', 'FacilityName', 'Address', 'City', 'State', 'Zip',
       'Latitude', 'Longitude', 'County', 'NAICS', 'SIC', 'UrbanRural',
       'Plant operator name', 'Balancing Authority Name',
       'Balancing Authority Code', 'NERC region acronym',
       'eGRID subregion acronym', 'Plant primary fuel',  # Fuel category missing!!!
       'Plant coal generation percent (resource mix)',
       'Plant oil generation percent (resource mix)',
       'Plant gas generation percent (resource mix)',
       'Plant nuclear generation percent (resource mix)',
       'Plant hydro generation percent (resource mix)',
       'Plant biomass generation percent (resource mix)',
       'Plant wind generation percent (resource mix)',
       'Plant solar generation percent (resource mix)',
       'Plant geothermal generation percent (resource mix)',
       'Plant other fossil generation percent (resource mix)',
       'Plant other unknown / purchased fuel generation percent (resource mix)'],
      dtype='object')
```

In its respective data file, the W column "Plant primary coal/oil/gas/ other fossil fuel category" represents the "PLFUELCT" keyword I am looking for in eGRID 2016.

egrid2016_data

In 2020, the now Y column name is changed to "Plant primary fuel category" (note the keyword is still "PLFUELCT") and, for some reason, is not provided in the data frame.

egrid2020_data

Would it be possible to include the PLFUELCT column in all eGRID facility datasets?

### PR DESCRIPTION
**Pull request by bl-young**
resolves #153

### CODE REVIEW

**Comment by dt-woods** [comment]
@bl-young, any idea when this patch might get released?

**Comment by bl-young** [comment]
@dt-woods remind me do you actually need a tagged version of the repo to incorporate this?

**Comment by dt-woods** [comment]
Not tagged, just incorporated. I guess this patch goes unmarked.

**Comment by bl-young** [comment]
I anticipate tagging it as 1.1.3, but may or may not try to resolve another error first unrelated to these egrid datasets.

**Comment by dt-woods** [comment]
FYI: I can confirm that `pip install --upgrade --force-reinstall git+https://github.com/USEPA/standardizedinventories#egg=StEWI` grabs the latest commit to master branch. Thanks.

**Pull request merged**
